version: 0.1.{build}
configuration: Release

image: Visual Studio 2017

skip_commits:
  files:
  - '**/*.md'
  - LICENSE

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

pull_requests:  
  do_not_increment_build_number: true

nuget:  
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(GitVersion_SemVer)'

init:
  - cmd: git config --global core.autocrlf true

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
  - ps: gitversion /l console /output buildserver

build:
  parallel: true
  publish_nuget: true
  verbosity: minimal

test:
  assemblies: '**\*.Tests.dll'

deploy:
- provider: NuGet
  api_key:
    secure: T9JXaUUdjl13atv7UAAW1LHVYuoo0c/NmAMir4g/iw95Ohl3DXCz7e3WloQ+I/8x
  on:
    branch: master
    appveyor_repo_tag: true
