version: 0.1.{build}
configuration: Release

image: Visual Studio 2017

clone_depth: 1

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

pull_requests:  
  do_not_increment_build_number: true

nuget:  
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

init:
  - cmd: git config --global core.autocrlf true

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
  - ps: gitversion /l console /output buildserver

build:
  parallel: true
  publish_nuget: true
  verbosity: minimal

test:
  assemblies: '**\*.Tests.dll'

deploy: off
